### ISSUE TITLE
ホットリロード対応にする

### ISSUE THREAD

**Issue by takanori-matsushita** [takanori-matsushita/echo-practice#1]
毎回サーバーを立ち上げ直さないといけないので、realizeを導入する。
[realize](https://github.com/oxequa/realize)

**Comment by takanori-matsushita** [comment]
`go get github.com/oxequa/realize`でrealizeをインストール

**Comment by takanori-matsushita** [comment]
以下のエラーが出てインストールできない。
```
go: finding github.com/oxequa/interact latest
go: github.com/oxequa/realize imports
        gopkg.in/urfave/cli.v2: gopkg.in/urfave/cli.v2@v2.2.0: parsing go.mod:
        module declares its path as: github.com/urfave/cli/v2
                but was required as: gopkg.in/urfave/cli.v2
```
go.modに以下を追記することでインストールできた。
`replace gopkg.in/urfave/cli.v2 => github.com/urfave/cli/v2 v2.2.0`

**Comment by takanori-matsushita** [comment]
realize.yamlを修正
realize startしたときに、指定のファイルをビルドして実行するようにする。これでファイルを編集し直したらホットリロードしてくれる。
```
  commands: {}
```
  ↓
```
  commands:
    install:
      status: true
      method: go build -o ./server ./server.go
    run:
      status: true
      method: ./server
```
